config/routes.rb
FayeChat::Application.routes.draw do

  root :to => "app#index"
  get '/login' => "app#login" , :as => 'login' #pour les liens 
  match '/login', :to => 'app#login' , :as => 'login'  #pour le formulaire 
  
  get '/logout' => "app#logout" , :as => 'logout'
  
  resources :users
  
  resources :messages
  
  

end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :user 

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :code, :presence => true , :uniqueness => true
    validates :password , :presence => true 
    validates :name , :presence => true , :uniqueness => true
    
    def self.authenticate(code="",password="")
        user = User.find_by_code(code)
        if user && user.password == password
            return user
        else 
            return false
        end 
    end
end

app/controllers/app_controller.rb
require 'net/http'

class AppController < ApplicationController
    
    before_filter :logged_in , :except => :login

    def index
    end

    def login
        if params[:user]
            code = params[:user][:code]
            password = params[:user][:password]
            @u = User.authenticate(code,password)
            
            if @u
                session[:user] = @u.id
                session[:name] = @u.name
                flash[:notice] = "Welcome man  :) #{@u.name}"
                publish("/newmember", {:id => @u.id, :name => @u.name ,:enter => true})
                @u.is_connected =true
                @u.connected_at = Time.now
                @u.save
                redirect_to messages_path
            else
                flash[:notice] = "Your are doing  bad stuffs here :("
            end
        end
    end

    def logout
        publish("/newmember",{:id => session[:user] ,:leave => true})
        @u = User.find(session[:user])
        @u.is_connected = false
        @u.connected_at = nil
        @u.save
        session[:user] = nil
        session[:name] = nil
        redirect_to login_path
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
  
  
  helper_method :logged_in
  
  def publish(channel="",data=nil)
    message = {:channel => channel, :data => data}
    uri= URI.parse("http://localhost:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end 
  
  protected 
  
  def logged_in
    if session[:user].nil?
        redirect_to login_path
        flash[:notice] = ":( el senior Bandi"
    end
  end 
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :logged_in 
  
  def index
    @users = User.order(:connected_at => "DESC").where(:is_connected => true).all
    @messages = Message.find(:all,:order => "id desc", :limit => 20).reverse
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end
  
  def create
    Message.create(:text => params[:message][:text],:user_id => params[:message][:user_id].to_i)
    publish("/newmessage",{:text => params[:message][:text], :user => session[:name]})
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :logged_in, :except => [:new,:create]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    if @user.save
        flash[:notice] = "Yeah !! good stuffs .User successfully created"
    else
        flash[:notice] = "Nop !! bad stuffs :(. User not created "
    end
    redirect_to login_path
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app/index.html.erb
<h1>App#index</h1>
<p>Find me in app/views/app/index.html.erb</p>

app/views/app/login.html.erb
<div>
<% if flash[:notice] %>
    <%= flash[:notice] %><br />
   
<% end %>
<%= link_to 'Creer mon compte', new_user_path %>

<%= form_tag login_path do%>
<table>
    <tr>
        <td>Code</td>
        <td><%= text_field :user,:code %></td>
    </tr>
    <tr>
        <td>Password</td>
        <td><%= password_field :user,:password %></td>
    </tr>
    <tr>
        <td></td>
        <td><%= submit_tag 'Connexion' %></td>
    </tr>
</table>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FayeChat</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "http://localhost:9292/faye.js","application" %>
  <%= csrf_meta_tags %>
</head>
<body >
    <div id="wrapper">
    <%= yield %>
    </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for Message.new, :remote => true do |f| %>
  
 <div class="field">
    <%= f.number_field :user_id , :type => 'hidden', :value => session[:user] %>
  </div>
  <div class="field">
    Message: <%= f.text_field :text %>
  </div>
<% end %>

app/views/messages/index.html.erb
<script type="text/javascript">

$(document).ready(function(){
    subscribe(client,"/newmember",newmember_handler);
    subscribe(client,"/newmessage",newmessage_handler);
    subscribe(client,"/writer",writer_handler);
    
    $('#new_message').submit(function(){
        $.post($(this).attr("action"),$(this).serialize(),null,"script");
        $('#message_text').val('');
        return false;
    });
    
    $("#message_text").keypress(function(event){
        if((event.which >= 32 && event.which <= 127) || event.which >= 256){
            publish(client,"/writer",{'id':$('#message_user_id').val(),'activity':true});
        }else{
            publish(client,"/writer",{'id':$('#message_user_id').val(),'activity':false});
        }
    });
    
    eval_nbr_utilisateur();
    scrollatbottom("chat_zone");
});

function eval_nbr_utilisateur(){
    var liste_utilisateurs = $("#liste_utilisateurs").find("li");
    var nbr =  liste_utilisateurs.length;
    $('#nbr_utilisateurs').html("Nombre d'utilisateurs:"+nbr);
}

function writer_handler(data){
    var activity = $('#liste_utilisateurs').find("#"+data.id);
    if(data.activity){
        activity.find("small").html("(writting)");
    }else {
        activity.find("small").html("");
    }
}

function scrollatbottom(id){
        var chat = $('#'+id).get(0);
        chat.scrollTop = chat.scrollHeight;
}

function newmessage_handler(data){
    if(data.text){
        var chat_content = "<span>"+data.user+" >> "+data.text+"</span><br/ >";
        $("#chat_zone").append(chat_content);
        scrollatbottom("chat_zone");
    }
};

function newmember_handler(data){
    if(data.enter){
        $('#liste_utilisateurs').append('<li id="'+data.id+'">'+data.name+'<small id="activity"></small></li>');
    }
    if(data.leave){
        var contact = $('#liste_utilisateurs').find("#"+data.id);
        $(contact).remove();
    }
    eval_nbr_utilisateur();
};

</script>
<div id="header">
    <div id="header_left">
        <%= session[:name] %>
    </div>
    <div id="header_right">
        <%= link_to 'Deconnexion' ,logout_path %>
    </div>
</div>
<div id="notification">
<%= notice %>
</div>
<div id = "chat_content">
    <div id="chat_message_form">
        <div id="chat_zone" >
            <% @messages.each do |message| %>
            <span><%= message.user.name %> >> <%= message.text %></span><br />
            <% end %>
        </div>
        <%= render 'form' %>
    </div>
    <div id="chat_users">
        <div id="nbr_utilisateurs"></div>
            <ul id="liste_utilisateurs">
                <% @users.each do |user| %>
                    <li id="<%= user.id %>"><%= user.name %> <small id="activity"></small></li>
                <% end %>
            </ul>
        </div>
    </div>
    <div id="footer">
        &copy; Aristide thomas mendoo
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password ,:type => 'password' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>|
<%= link_to 'Back', users_path %>